# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ main ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - '*'

jobs:
  deploy_version:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x
      - name: Get release notes
        run: |
          bash cicd/create-release-notes.sh ${{ env.GITHUB_REF_SLUG }} ${{ env.build }} ${{ env.IMAGE_TAG }}
      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            body_path: RELEASE_NOTES.md
            draft: false
            prerelease: false